# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
   adapter: postgresql
   encoding: unicode
   database: simple_development
   pool: 5
   username: postgresql
   password: postgresql

test:
   adapter: postgresql
   encoding: unicode
   database: simple_test
   pool: 5
   username: postgresql
   password: postgresql

production:
   adapter: postgresql
   encoding: unicode
   database: simple_production
   pool: 5
   username: postgresql
   password: postgresql